### ISSUE TITLE
files - exception to "no blocking operations"

### ISSUE THREAD

**Issue by dckc** [ponylang/pony-patterns#16]
The waiting pattern says "One of Pony's key features is there are no blocking operations."

The files package is an exception; see https://github.com/ponylang/ponyc/issues/681

**Comment by SeanTAllen** [comment]
We'd welcome a PR. I don't consider synchronous and blocking to be synonyms. You apparently do.

**Comment by SeanTAllen** [comment]
Synchronous operations aren't considered a bug. So I'll take that as a no.
