### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Charlesetc** [ponylang/pony-patterns#19]
I noticed there's no syntax highlighting in this [book](https://patterns.ponylang.org/) but there is in the tutorial.

**Comment by SeanTAllen** [comment]
Thanks for pointing that out @Charlesetc. The only reason for it was that the book hadn't been rebuilt since hightlight.js got Pony support. I rebuilt it and syntax highlighting is working. Thanks.

**Comment by Charlesetc** [comment]
Yay! 🍐
