### ISSUE TITLE
Broken link on Copying to Persistent DS

### ISSUE THREAD

**Issue by rhagenson** [ponylang/pony-patterns#44]
There is a link on the Data Sharing -> Copying page to persistent data structures which contains an extra `/data-sharing/` it is URL so does not link properly.

**Comment by SeanTAllen** [comment]
@rhagenson if you aren't working on a fix for this, i'll take it now.

**Comment by rhagenson** [comment]
I was not. It was a case of noticed it and off to other things. Thank you
for closing it.
