### ISSUE TITLE
waiting without time

### ISSUE THREAD

**Issue by Theodus** [ponylang/pony-patterns#7]
Waiting is described only with the use of time. I realize that non-blocking operations are an important part of Pony, but I think that there should be a way of allowing an actor to wait for signals during a behavior rather than having its methods called. Am I missing something about behaviors or is this functionality intentionally removed?

**Comment by SeanTAllen** [comment]
@Theodus this sounds like something you would want to bring up on the mailing list as it isnt an issue with something being incorrect in pony patterns.

**Comment by Theodus** [comment]
Alright, sorry about that.
